name: Auto-grades your solution

on: push

jobs:
  compiles:
    name: "Runs `make compile`"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: make compile

  parts:
    name: "Grades assignment"
    runs-on: ubuntu-latest
    needs: [compiles]
    strategy:
      fail-fast: false
      matrix:
        part: [ 1, 2, 3, 4, 5, 6 ]
    steps:
      - name: Checkout template repository
        uses: actions/checkout@master

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
        
      - name: Compile the compiler
        run: make compile

      - name: Downloads JPL runtime
        uses: actions/checkout@master
        with:
          repository: utah-cs4470-sp25/runtime
          path: rt

      - name: Setup runtime
        run: |
          (cd rt && ./configure --prefix /home/runner/work/jpl-bhargav/jpl-bhargav/rt/libpng-1.6.43/target 2>&1 | tee config.log)
        
      - name: Check if config.log exists and print it
        run: |
          if [ -f config.log ]; then
            echo "config.log contents:"
            cat config.log
          else
            echo "config.log not found"
          fi

      - name: "Downloads grader scripts"
        uses: actions/checkout@master
        with:
          repository: utah-cs4470-sp25/grader
          path: grader
          
      - name: "Counts total parts"
        run: echo HW_PARTS=$(make -s -C grader count-current) >> $GITHUB_ENV; echo $HW_PARTS 
        
      - name: Total of ${{ env.HW_PARTS }} parts
        run: true
        
      - name: Grade part ${{ matrix.part }}
        if: matrix.part <= env.HW_PARTS
        timeout-minutes: 5
        run: make -C grader test-current DIR=$GITHUB_WORKSPACE PART=${{ matrix.part }}
